apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-sample-web
  labels:
    app: chat-sample-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-sample-web
  template:
    metadata:
      labels:
        app: chat-sample-web
    spec:
      containers:
      - name: chat-sample-web
        image: thakarchinmay/chat-sample-web:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-sample-web-svc
  labels:
    app: chat-sample-web
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: chat-sample-web
